# Generated by Django 4.2.30 on 2026-04-09 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_fellowships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meeting_day', models.CharField(max_length=20)),
                ('meeting_time', models.TimeField()),
                ('venue', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fellowship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='structure.fellowship')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_cells', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BibleStudyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='structure.cell')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['fellowship', 'name'], name='structure_c_fellows_3b51b9_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['leader'], name='structure_c_leader__c702c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('fellowship', 'name'), name='uniq_cell_name_per_fellowship'),
        ),
        migrations.AddIndex(
            model_name='biblestudyclass',
            index=models.Index(fields=['cell', 'name'], name='structure_b_cell_id_1d4020_idx'),
        ),
        migrations.AddIndex(
            model_name='biblestudyclass',
            index=models.Index(fields=['teacher'], name='structure_b_teacher_957553_idx'),
        ),
        migrations.AddConstraint(
            model_name='biblestudyclass',
            constraint=models.UniqueConstraint(fields=('cell', 'name'), name='uniq_class_name_per_cell'),
        ),
    ]
