# Generated by Django 4.2.30 on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="meeting_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cell",
            name="venue",
            field=models.TextField(blank=True, default=""),
        ),
    ]
