# Generated by Django 4.2.30 on 2026-04-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_responsibility_and_user_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('pastor', 'Pastor'), ('staff', 'Church Staff'), ('fellowship_leader', 'Fellowship Leader'), ('cell_leader', 'Cell Leader'), ('teacher', 'Bible Study Teacher'), ('member', 'Member')], db_index=True, default='member', max_length=30),
        ),
    ]
