# Generated by Django 4.2.30 on 2026-04-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home_address",
            field=models.TextField(blank=True),
        ),
    ]
