# Generated by Django 4.2.30 on 2026-04-16 12:00

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["day_of_week", "start_time", "name"],
            },
        ),
        migrations.AddField(
            model_name="attendance",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="members.churchservice",
            ),
        ),
        migrations.AddIndex(
            model_name="churchservice",
            index=models.Index(fields=["is_active", "day_of_week"], name="members_chu_is_acti_3075f9_idx"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["date", "service"], name="members_att_date_9cdf70_idx"),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("member", "date", "service"),
                name="uniq_member_attendance_per_church_service",
                condition=Q(service__isnull=False),
            ),
        ),
    ]
