# Generated by Django 4.2.30 on 2026-04-18 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_memberprofile_visitation_leaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitation_date', models.DateField()),
                ('visitation_time', models.TimeField()),
                ('method_used', models.CharField(choices=[('calling', 'Calling'), ('one_on_one_visitation', 'One on One Visitation')], max_length=32)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visitation_reports', to=settings.AUTH_USER_MODEL)),
                ('assigned_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_visitation_reports', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitation_reports', to='members.memberprofile')),
            ],
            options={
                'ordering': ['-visitation_date', '-visitation_time', '-id'],
                'indexes': [models.Index(fields=['assigned_leader', 'status'], name='members_vis_assigne_80a8c0_idx'), models.Index(fields=['member', 'status'], name='members_vis_member__e44801_idx'), models.Index(fields=['status', 'visitation_date'], name='members_vis_status_7f30e2_idx')],
            },
        ),
    ]
