# Generated by Django 4.2.30 on 2026-04-19 05:41

from django.db import migrations, models
import django.db.models.deletion


def backfill_person_domain(apps, schema_editor):
    MemberProfile = apps.get_model("members", "MemberProfile")
    Person = apps.get_model("members", "Person")
    Attendance = apps.get_model("members", "Attendance")
    CellMembership = apps.get_model("members", "CellMembership")

    for profile in MemberProfile.objects.select_related("user", "cell").all():
        if profile.person_id:
            person = profile.person
        else:
            user = profile.user
            person = Person.objects.create(
                first_name=(getattr(user, "first_name", "") or getattr(user, "username", "") or "Member"),
                last_name=(getattr(user, "last_name", "") or ""),
                phone=(getattr(user, "phone", "") or ""),
                email=(getattr(user, "email", "") or ""),
            )
            profile.person_id = person.id

        if profile.is_first_timer:
            profile.membership_status = "first_timer"
        elif profile.foundation_completed or profile.is_partner:
            profile.membership_status = "member"
        elif profile.last_attended:
            profile.membership_status = "regular"
        else:
            profile.membership_status = "visitor"

        profile.save(update_fields=["person", "membership_status", "updated_at"])

        if profile.cell_id:
            CellMembership.objects.get_or_create(
                person_id=person.id,
                cell_id=profile.cell_id,
                defaults={"is_active": True},
            )

    for attendance in Attendance.objects.select_related("member", "member__person").all():
        if attendance.member_id and attendance.member and attendance.member.person_id:
            attendance.person_id = attendance.member.person_id
            attendance.save(update_fields=["person"])


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("structure", "0001_initial"),
        ("members", "0004_visitationreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["first_name", "last_name", "id"]},
        ),
        migrations.CreateModel(
            name="CellMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_memberships",
                        to="structure.cell",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_memberships",
                        to="members.person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="person",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_profile",
                to="members.person",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_attendance_records",
                to="members.person",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="members.memberprofile",
            ),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="membership_status",
            field=models.CharField(
                choices=[
                    ("visitor", "Visitor"),
                    ("first_timer", "First Timer"),
                    ("regular", "Regular Attender"),
                    ("member", "Member"),
                ],
                default="visitor",
                max_length=20,
                db_index=True,
            ),
        ),
        migrations.RunPython(backfill_person_domain, noop),
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date", "person__first_name", "person__last_name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="memberprofile",
            options={"ordering": ["person__first_name", "person__last_name", "user__username"]},
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["person", "date"], name="members_att_person__4a9d0d_idx"),
        ),
        migrations.AddIndex(
            model_name="memberprofile",
            index=models.Index(fields=["membership_status"], name="members_mem_members_b36f5a_idx"),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("person__isnull", False)),
                fields=("person", "date", "service_type"),
                name="uniq_person_attendance_per_service",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("person__isnull", False), ("service__isnull", False)),
                fields=("person", "date", "service"),
                name="uniq_person_attendance_per_church_service",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["first_name", "last_name"], name="members_per_first_n_c29077_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["phone"], name="members_per_phone_101b30_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["email"], name="members_per_email_9766f1_idx"),
        ),
        migrations.AddIndex(
            model_name="cellmembership",
            index=models.Index(fields=["cell", "is_active"], name="members_cel_cell_id_b1c5ce_idx"),
        ),
        migrations.AddIndex(
            model_name="cellmembership",
            index=models.Index(fields=["person", "is_active"], name="members_cel_person__7e4ecf_idx"),
        ),
        migrations.AddConstraint(
            model_name="cellmembership",
            constraint=models.UniqueConstraint(fields=("person", "cell"), name="uniq_person_cell_membership"),
        ),
    ]
