# Generated by Django 4.2.30 on 2026-04-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_member_status_from_leaders'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTimerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('cell', 'Cell'), ('service', 'Service')], max_length=20)),
                ('event_date', models.DateField()),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_timer_events', to='members.person')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
                'indexes': [models.Index(fields=['event_type', 'handled'], name='members_fir_event_t_a9b1a7_idx'), models.Index(fields=['person', 'event_type'], name='members_fir_person__fcd8a9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='firsttimerevent',
            constraint=models.UniqueConstraint(fields=('person', 'event_type'), name='uniq_first_timer_event_per_source'),
        ),
    ]
