# Generated by Django 4.2.30 on 2026-04-09 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CellReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(db_index=True)),
                ('attendance_count', models.PositiveIntegerField()),
                ('new_members', models.PositiveIntegerField(default=0)),
                ('offering_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='structure.cell')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meeting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.cellreport')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.cellreport')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['report', 'created_at'], name='reports_rep_report__32ad4d_idx'), models.Index(fields=['author'], name='reports_rep_author__b7f270_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('commented', 'Commented')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='reports.cellreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report', 'created_at'], name='reports_rep_report__3e8680_idx'), models.Index(fields=['action'], name='reports_rep_action_eb6de4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cellreport',
            index=models.Index(fields=['cell', 'meeting_date'], name='reports_cel_cell_id_983896_idx'),
        ),
        migrations.AddIndex(
            model_name='cellreport',
            index=models.Index(fields=['status', 'meeting_date'], name='reports_cel_status_8728dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='cellreport',
            constraint=models.UniqueConstraint(fields=('cell', 'meeting_date'), name='uniq_report_per_cell_per_date'),
        ),
    ]
