# Generated by Django 4.2.30 on 2026-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellreport',
            name='attendee_names',
            field=models.TextField(blank=True),
        ),
    ]
