# Generated by Django 4.2.30 on 2026-04-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_churchservice_attendance_service"),
        ("reports", "0002_report_attendees_and_attendance_count_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellreport",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="members.churchservice",
            ),
        ),
    ]
