# Generated by Django 4.2.30 on 2026-04-18 11:10

from django.db import migrations, models


def populate_report_type(apps, schema_editor):
    CellReport = apps.get_model("reports", "CellReport")

    for report in CellReport.objects.all().only("id", "meeting_date"):
        meeting_date = report.meeting_date
        week_of_month = ((meeting_date.day - 1) // 7) + 1
        if week_of_month <= 1:
            value = "week1_prayer_planning"
        elif week_of_month == 2:
            value = "week2_bible_study"
        elif week_of_month == 3:
            value = "week3_bible_study"
        else:
            value = "week4_outreach"
        CellReport.objects.filter(pk=report.pk).update(report_type=value)


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_cellreport_attendee_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("week1_prayer_planning", "Week 1 - Prayer and Planning"),
                    ("week2_bible_study", "Week 2 - Bible Study"),
                    ("week3_bible_study", "Week 3 - Bible Study"),
                    ("week4_outreach", "Week 4 - Outreach"),
                ],
                default="week1_prayer_planning",
                max_length=32,
            ),
        ),
        migrations.RunPython(populate_report_type, migrations.RunPython.noop),
    ]
