# Generated by Django 4.2.30 on 2026-04-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_memberprofile_visitation_leaders'),
        ('reports', '0003_cellreport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellreport',
            name='first_timer_attendees',
            field=models.ManyToManyField(blank=True, related_name='first_timer_reports', to='members.memberprofile'),
        ),
        migrations.AddField(
            model_name='cellreport',
            name='meeting_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cellreport',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
