# Generated by Django 4.2.30 on 2026-04-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_cellmembership_person_alter_attendance_options_and_more'),
        ('reports', '0004_cellreport_first_timer_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellreport',
            name='attendees',
            field=models.ManyToManyField(related_name='cell_reports', to='members.person'),
        ),
        migrations.AlterField(
            model_name='cellreport',
            name='first_timer_attendees',
            field=models.ManyToManyField(blank=True, related_name='first_timer_reports', to='members.person'),
        ),
    ]
