# Generated by Django 4.2.30 on 2026-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_cellreport_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellreport',
            name='review_summary',
            field=models.TextField(blank=True),
        ),
    ]
