# Generated by Django 4.2.30 on 2026-04-20 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('all_day', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('service', 'Service'), ('meeting', 'Meeting'), ('counseling', 'Counseling'), ('outreach', 'Outreach'), ('training', 'Training'), ('administrative', 'Administrative'), ('other', 'Other')], db_index=True, default='meeting', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='schedule_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime', 'title'],
                'indexes': [models.Index(fields=['start_datetime', 'end_datetime'], name='scheduling__start_d_746e6f_idx'), models.Index(fields=['created_by', 'start_datetime'], name='scheduling__created_d41ef3_idx')],
            },
        ),
    ]
